name: Capsule CI

on:
  push:
    branches:
      - master

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Lint & Tests
        run: |
          yarn
          yarn lint
          yarn test
      - name: Deploy to Github pages
        uses: guillaumejparis/gh-actions-deploy-gh-pages@master
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_BLOUP_KEY }}
